name: fl_env
channels:
  - conda-forge
dependencies:
  - pip=23.0.1=pyhd8ed1ab_0
  - python=3.11.8
  - pip:
    - appdirs==1.4.4
    - certifi==2022.12.7
    - charset-normalizer==3.1.0
    - click==8.1.3
    - contourpy==1.0.7
    - cycler==0.11.0
    - docker-pycreds==0.4.0
    - filelock==3.10.0
    - fonttools==4.39.2
    - gitdb==4.0.10
    - gitpython==3.1.31
    - idna==3.4
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mpmath==1.3.0
    - networkx==3.0
    - numpy==1.24.2
    - packaging==23.0
    - pathtools==0.1.2
    - pillow==9.4.0
    - protobuf==3.20.3
    - psutil==5.9.4
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pyyaml==6.0
    - requests==2.28.2
    - sentry-sdk==1.18.0
    - setproctitle==1.3.2
    - six==1.16.0
    - smmap==5.0.0
    - sympy==1.11.1
    - tensorboardx==2.6
    - torch==2.0.0
    - torchvision==0.15.1
    - tqdm==4.65.0
    - typing-extensions==4.5.0
    - urllib3==1.26.15
    - wandb==0.14.0
    - gdown==5.1.0
    - pandas==2.1.1
    - wget==3.2
    - parse==1.19.1
    - prettytable==3.9.0
    - scikit-learn==1.3.0
    - loguru==0.7.0
    - numpy==1.23.5
