dataset:
  dataset_name: fashionmnist
  data_dir: ./data
  num_classes: 10
model:
  model_name: CNNFashionMNIST
training_params:
  seed: 0
fl_parameters:
  num_clients: 100
  fl_method: qFedAvg
  frac: 0.3
  q: 0.1
global_parameters:
  global_rounds: 250
  global_learning_rate: 1
client_parameters:
  local_bs: 256
  local_lr: 1e-2
  local_epochs: 5
split_params:
  split_type: non-iid
  dirichlet_param: 0.5
  min_proportion: 0.002
