dataset: ['synthetic'] #, "tiny-imagenet", "utkface"]
model: ["mlp"]#, 'vgg11_bn', 'resenet18', 'resnet9']
epochs: [10]
lr: [0.01]
distribution: ["non_iid"]
num_users: [100]
frac: [0.5]
local_ep: [5]
local_bs: [256]
q: [0.01, 0.001] #qfedavg,
fl_method:  ['FedSyn']
mu: [0.01]
sparsification_ratio: [0.2, 0.5] #fedsyn
min_sparsification_ratio: [0.1]
sparsification_type: ["rtopk"] #fedsyn
dirichlet_param: [0.5, 0.8]
use_fair_sparsification: [0, 1] #fedsyn
seed: [1234, 42]
