dataset: ['cifar'] #, "cifar"] # , "tiny-imagenet",
model: ["small_cnn"] # 'vgg11_bn', 'small_cnn'] #'resenet18',
epochs: [30]
lr: [0.01]
distribution: ["non_iid"]
num_users: [100]
frac: [0.5]
local_ep: [5]
local_bs: [256]
# q: [0.001, 0.01] #qfedavg,
fl_method:  ['FedSyn'] #'FedAvg',  'FedSyn'] 'qFedAvg'
mu: [0.01]
sparsification_ratio: [0.3] #fedsyn
sparsification_type: ['topk', "rtopk"] #fedsyn
min_sparsification_ratio: [0.1]
dirichlet_param: [0.8]
use_fair_sparsification: [0, 1] #fedsyn
seed: [42] #1234
fairness_temperature: [1, 5]
