dataset:
  dataset_name: CIFAR10
  data_dir: ./data
  num_classes: 10
model:
  model_name: ResNet9
training_params:
  seed: 0
fl_parameters:
  num_clients: 100
  fl_method: FedAvg
  frac: 0.1
global_parameters:
  global_rounds: 250
  global_learning_rate: 1
client_parameters:
  local_bs: 256
split_params:
  split_type: non-iid
  dirichlet_param: 0.5
  min_proportion: 0.002