dataset:
  dataset_name: CIFAR10
  data_dir: ./data
  num_classes: 10
model:
  model_name: ResNet9
training_params:
  seed: 0
fl_parameters:
  num_clients: 100
  fl_method: FedSyn
  sparsification_type: rtopk
  use_fair_sparsification: True
  frac: 0.3
  fairness_function: linear-interpolate
global_parameters:
  global_rounds: 250
  global_learning_rate: 1
client_parameters:
  local_bs: 256
  local_lr: 1e-2
  local_epochs: 5
split_params:
  split_type: non-iid
  dirichlet_param: 0.5
  min_proportion: 0.002