dataset: ['synthetic']
model: ["logistic", "MLP"]
epochs: [30]
lr: [0.01] 
distribution: ["non_iid", "iid", "majority_minority"]
num_users: [50]
frac: [0.5]
local_ep: [3]
local_bs: [128]
q: [0.001, 0.01]
fl_method:  ['FedSyn', "qFedAvg"] 
mu: [0.01]
sparsification_ratio: [0.2, 0.4, 0.6, 0.8, 1] 
sparsification_type: ['rtopk', "topk", "randk"]
min_sparsification_ratio: [0.1]
dirichlet_param: [0.8]
use_fair_sparsification: [0, 1]
seed: [42]
fairness_temperature: [1]
majority_proportion: [0.8]
majority_minority_overlap: [0.5]
num_features: [20]
num_classes: [20]
gdrive_id: "1ANMMlbmTwg4JiggXE8FqFOg-ZErMlZzi"
