dataset: ["vehicle"]
model: ["resnet9"]
epochs: [50]
lr: [0.01] 
iid: [0]
num_users: [100]
frac: [0.5]
local_ep: [1]
local_bs: [256]
q: [5]
fl_method:  ['qffedavg']
mu: [0.01]
dist_noniid: [0.5]
seed: [42]
sparsification_ratio: [0.2]
sparsification_type: ['topk']
use_fair_sparsification: [0]