dataset: ['synthetic']
model: ["MLP"]
epochs: [10]
lr: [0.01] 
distribution: ["non_iid", "iid", "majority_minority"]
num_users: [100]
frac: [0.5]
local_ep: [5]
local_bs: [256]
fl_method:  ['FedSyn'] 
mu: [0.01]
sparsification_ratio: [0.3] 
sparsification_type: ['topk']
min_sparsification_ratio: [0.1]
dirichlet_param: [0.8]
use_fair_sparsification: [0]
seed: [42]
fairness_temperature: [1]
data_path: ['data/synthetic_data.json']
num_features: [60]
num_classes: [10]