num_users: [10, 25, 50, 100]
dataset: ["mnist", "cifar", "fashionmnist"]
epochs: [30]
lr: [0.001, 0.001, 0.0005]
local_ep: [1, 3, 5]
frac: [0.1, 0.3, 1]
iid: [0, 1]
dist_noniid: [0.3, 0.5]
mu:  [0.01, 0.001]
fl_method: ["FedAvg", "FedProx"]
reweight_loss_avg: [0,1]
seed: [1234]