dataset: ["vehicle"]
model: ["svm", "lr", "mclr"]
epochs: [5]
lr: [0.01] 
iid: [0]
num_users: [100]
frac: [0.5]
local_ep: [1]
local_bs: [256]
q: [5]
fl_method:  ['qFedAvg']
mu: [0.01]
iid: [1]
dist_noniid: [0]
seed: [42]
sparsification_ratio: [0.2]
sparsification_type: ['topk']
use_fair_sparsification: [0]