dataset: ["tiny-imagenet"]
model: ['resnet18']
epochs: [50]
lr: [0.01]
distribution: [non_iid]
num_users: [100]
frac: [0.5]
local_ep: [5]
local_bs: [16]
q: [0.01, 0.001] #qfedavg,
fl_method:  ['qFedAvg', 'FedSyn']
mu: [0.01]
sparsification_ratio: [0.2, 0.5] #fedsyn
sparsification_type: ['rtopk', 'topk'] #fedsyn
dirichlet_param: [0.5, 0.8]
use_fair_sparsification: [0, 1] #fedsyn
seed: [42]
