dataset:
  dataset_name: CIFAR10 
  data_dir: ./data
  num_clients: 10
  num_classes: 10
SVHN_data:
  extra: True
model:
  model_name: SmallCNN 
training_params:
  seed: 0
fl_parameters:
  num_clients: 10
  fl_method: FedSyn 
  frac: 0.2
  use_fair_sparisification: True
global_parameters:
  global_rounds: 10
  client_frac: 0.3
  global_learning_rate: 1
client_parameters:
  local_bs: 10
  local_lr: 1e-3
  local_epochs: 3
split_params:
  split_type: majority_minority
  dirichlet_param: 10
  min_proportion: 0.09